services:
    _defaults:
        autoconfigure: true

    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ['setFramework', ['@contao.framework']]

    Janborg\ContaoIcal\Migration\StartdateEnddateMigration:
        arguments:
            - '@database_connection'
            - '@contao.framework'